spring.application.name=configserver

server.port=8888
spring.cloud.config.server.git.uri=https://gitlab.stackroute.in/Selvakumar/wipro-config-repo
spring.cloud.config.server.git.username=r.selvakumar@stackroute.in
spring.cloud.config.server.git.password=Keerthi#123
spring.cloud.config.server.git.skip-ssl-validation=true
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true



